FROM golang:1.9.4

ADD . /go/src/boomer
WORKDIR /go/src/boomer

RUN curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
# Recompile everything and create a static binary
ENV CGO_ENABLED=0
RUN dep ensure